# Generated by Django 5.1.3 on 2024-11-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_alter_todo_finished_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
