# Generated by Django 5.1.3 on 2024-11-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0005_alter_todo_deadline_alter_todo_finished_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="created_at",
            field=models.DateField(auto_now_add=True, verbose_name="Criado em"),
        ),
        migrations.AlterField(
            model_name="todo",
            name="deadline",
            field=models.Field(verbose_name="Data final"),
        ),
        migrations.AlterField(
            model_name="todo",
            name="finished_at",
            field=models.DateField(null=True, verbose_name="Entregue em"),
        ),
    ]
